source 'https://rubygems.org'
ruby '2.2.0'

gem 'jekyll'
gem 'jekyll-assets'
gem 'foreman'
gem 'thin'
gem 'rack-contrib'
#gem 'rack-jekyll'
gem 'kramdown'
gem 'rake'
gem 'sass'
gem 'uglifier'
#gem 'github-pages'
